<?php
require_once __DIR__ . '/include/auth.php';

// Redirect to Welcome animation unless returning from it
if (!isset($_GET['welcome'])) {
    header("Location: Welcome.php");
    exit;
}

if (is_logged_in()) {
    header("Location: dashboard.php");
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edu-Planning — Intelligent Academic Platform UCA</title>
    <link rel="icon" type="image/png" href="assets/images/universite-cadi-ayyad.png">
    <meta name="description"
        content="Edu-Planning, the intelligent academic platform of Université Cadi Ayyad. AI-generated personalized revision schedules, module tracking, and grade management.">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,600;0,700;0,900;1,600&family=Roboto:wght@300;400;500;600&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400&display=swap"
        rel="stylesheet">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Animations CSS removed (file not present) -->

    <link rel="stylesheet" href="css/index.css">
</head>

<body>
    <!-- Advanced Mouse Follower -->
    <div id="cursor-dot"></div>
    <div id="cursor-ring"></div>

    <!-- ════════════════════════════════════════
        NAVBAR
        ════════════════════════════════════════ -->
    <nav class="navbar navbar-expand-lg navbar-premium" id="main-navbar">
        <div class="container">
            <a class="navbar-brand" href="index.php">
                <img src="assets/images/universite-cadi-ayyad.png" alt="UCA">
                Edu-Planning
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-label="Menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto align-items-center gap-1">
                    <li class="nav-item anim-fade-down delay-200">
                        <a class="nav-link" href="#about">About</a>
                    </li>
                    <li class="nav-item anim-fade-down delay-300">
                        <a class="nav-link" href="#features">Features</a>
                    </li>
                    <li class="nav-item anim-fade-down delay-400">
                        <a class="nav-link" href="#how-it-works">How It Works</a>
                    </li>
                </ul>
                <div class="d-flex gap-2 ms-lg-4 anim-fade delay-500">
                    <a href="login.php" class="btn-nav-outline" id="nav-login">Login</a>
                    <a href="register.php" class="btn-nav-gold" id="nav-register">Sign Up</a>
                </div>
            </div>
        </div>
    </nav>

    <!-- ════════════════════════════════════════
        HERO SECTION
        ════════════════════════════════════════ -->
    <section class="hero-section" id="hero">
        <div class="hero-bg"></div>
        <!-- Floating particles (generated by JS) -->
        <div class="hero-particles" id="hero-particles"></div>

        <div class="container position-relative" style="z-index:2;">
            <div class="hero-content">
                <!-- UCA badge -->
                <div class="hero-logo-badge">
                    <img src="assets/images/universite-cadi-ayyad.png" alt="UCA">
                    <span>Université Cadi Ayyad — Marrakech</span>
                </div>

                <!-- Typewriter title -->
                <h1 class="hero-title">
                    <span class="typewriter-text" id="hero-typewriter">Intelligent Academic Planning</span>
                </h1>

                <!-- Subtitle -->
                <p class="hero-subtitle-text">
                    Generate a <em>personalized</em> revision schedule based on your academic performance and optimize
                    your success at UCA.
                </p>

                <!-- CTA buttons -->
                <div class="hero-cta">
                    <a href="register.php" class="btn-hero-primary" id="cta-main">
                        <i class="fas fa-rocket"></i> Get Started Now
                    </a>
                    <a href="login.php" class="btn-hero-secondary" id="cta-secondary">
                        <i class="fas fa-sign-in-alt"></i> Access My Space
                    </a>
                </div>
            </div>
        </div>

        <!-- Scroll hint -->
        <div class="hero-scroll-hint">
            <i class="fas fa-chevron-down"></i>
            <span>Discover</span>
        </div>
    </section>

    <!-- ════════════════════════════════════════
    ABOUT SECTION
    ════════════════════════════════════════ -->
    <section class="section-spacing" id="about"
        style="background: rgba(184, 134, 11, 0.03); border-top: 1px solid rgba(255, 255, 255, 0.05); border-bottom: 1px solid rgba(255, 255, 255, 0.05);">
        <div class="container">
            <div class="row align-items-center g-5">
                <div class="col-lg-6 scroll-reveal delay-100">
                    <div style="position: relative; width: 280px; height: 280px; margin: 0 auto;">
                        <div id="stl-viewer"
                            style="width: 100%; height: 100%; display: block; filter: drop-shadow(0 0 20px rgba(184, 134, 11, 0.3)); cursor: grab;">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 scroll-reveal delay-200">
                    <span class="section-eyebrow" style="text-align: left; display: block;">About The Platform</span>
                    <h2 class="section-title" style="text-align: left; font-size: 36px; margin-bottom: 24px;">
                        Transforming Academic Management at UCA</h2>
                    <p style="font-size: 16px; line-height: 1.8; margin-bottom: 20px; color: #7A7A7A;">
                        Edu-Planning is a modern, AI-powered academic workspace engineered specifically for Université
                        Cadi Ayyad students. We replace fragmented notes and scattered deadlines with a unified,
                        intelligent dashboard that keeps you in complete control of your educational journey.
                    </p>
                    <p style="font-size: 16px; line-height: 1.8; margin-bottom: 30px; color: #7A7A7A;">
                        From comprehensive module tracking and dynamic progress analytics to personalized, AI-generated
                        study schedules, Edu-Planning provides the cutting-edge tools you need to optimize your
                        revisions, conquer your exams, and achieve sustained academic excellence.
                    </p>
                    <a href="register.php" class="btn-hero-primary" style="padding: 12px 24px; font-size: 14px;">
                        Join The Community <i class="fas fa-arrow-right ms-2"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- ════════════════════════════════════════
    FEATURES SECTION
    ════════════════════════════════════════ -->
    <section class="section-spacing" id="features">
        <div class="container">
            <div class="text-center mb-2">
                <span class="section-eyebrow">Our Platform</span>
                <h2 class="section-title">Key Features</h2>
                <p class="section-subtitle">A complete solution designed to optimize your academic journey at UCA</p>
            </div>

            <div class="row g-4 mt-2">
                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-100">
                        <div class="feature-icon"><i class="fas fa-layer-group"></i></div>
                        <h4>Smart Module Tracking</h4>
                        <p>Centralize all your coursework. Monitor difficulty levels, track comprehension, and manage
                            your academic pipeline in one intuitive dashboard.</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-200">
                        <div class="feature-icon"><i class="fas fa-brain"></i></div>
                        <h4>Adaptive AI Planning</h4>
                        <p>Generate highly personalized revision schedules using advanced algorithms that adapt to your
                            study pace, ensuring optimal focus for every deadline.</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-300">
                        <div class="feature-icon"><i class="fas fa-calendar-check"></i></div>
                        <h4>Deadline Management</h4>
                        <p>Never miss a critical date. Our system prioritizes your upcoming exams, ensuring your focus
                            is always directed where it matters most.</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-200">
                        <div class="feature-icon"><i class="fas fa-user-shield"></i></div>
                        <h4>Secure Profiles</h4>
                        <p>Maintain total control over your academic data with robust, encrypted user authentication and
                            personalized profile management.</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-300">
                        <div class="feature-icon"><i class="fas fa-chart-pie"></i></div>
                        <h4>Visual Analytics</h4>
                        <p>Gain immediate insights into your performance through beautiful, real-time interactive charts
                            and progress indicators.</p>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-card scroll-reveal delay-400">
                        <div class="feature-icon"><i class="fas fa-bolt"></i></div>
                        <h4>Actionable Insights</h4>
                        <p>Turn your academic data into actionable steps. Instantly know which modules require more
                            attention based on exam proximity and difficulty.</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- ════════════════════════════════════════
        HOW IT WORKS SECTION
        ════════════════════════════════════════ -->
    <section class="section-spacing" id="how-it-works"
        style="background: rgba(184, 134, 11, 0.03); border-top: 1px solid var(--border-color); border-bottom: 1px solid var(--border-color);">
        <div class="container">
            <div class="text-center mb-5">
                <span class="section-eyebrow">Workflow</span>
                <h2 class="section-title">How It Works</h2>
                <p class="section-subtitle">Three simple steps to academic success</p>
            </div>

            <div class="row g-4 position-relative">
                <!-- Connecting Line for Desktop -->
                <div class="d-none d-lg-block"
                    style="position: absolute; top: 45px; left: 15%; right: 15%; height: 2px; background: linear-gradient(90deg, transparent, var(--gold-primary), transparent); z-index: 1;">
                </div>

                <div class="col-lg-4 z-2">
                    <div class="text-center scroll-reveal delay-100"
                        style="background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px; padding: 30px 20px; height: 100%; position: relative;">
                        <div
                            style="width: 60px; height: 60px; background: var(--bg-body); border: 2px solid var(--gold-primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; color: var(--gold-primary); margin: 0 auto 20px; font-weight: 800; font-family: 'Playfair Display', serif;">
                            1</div>
                        <h4 style="color: var(--heading-color); font-weight: 700; margin-bottom: 15px;">Add Modules</h4>
                        <p style="color: var(--text-muted); font-size: 14px; line-height: 1.6;">Input your subjects,
                            exam dates, difficulty levels, and current progress into your personalized dashboard.</p>
                    </div>
                </div>

                <div class="col-lg-4 z-2">
                    <div class="text-center scroll-reveal delay-200"
                        style="background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px; padding: 30px 20px; height: 100%; position: relative;">
                        <div
                            style="width: 60px; height: 60px; background: var(--bg-body); border: 2px solid var(--gold-primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; color: var(--gold-primary); margin: 0 auto 20px; font-weight: 800; font-family: 'Playfair Display', serif;">
                            2</div>
                        <h4 style="color: var(--heading-color); font-weight: 700; margin-bottom: 15px;">Generate Plan
                        </h4>
                        <p style="color: var(--text-muted); font-size: 14px; line-height: 1.6;">Select the modules you
                            want to focus on and let our AI create an optimized 7-day revision schedule.</p>
                    </div>
                </div>

                <div class="col-lg-4 z-2">
                    <div class="text-center scroll-reveal delay-300"
                        style="background: var(--bg-surface); border: 1px solid var(--border-color); border-radius: 12px; padding: 30px 20px; height: 100%; position: relative;">
                        <div
                            style="width: 60px; height: 60px; background: var(--bg-body); border: 2px solid var(--gold-primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; color: var(--gold-primary); margin: 0 auto 20px; font-weight: 800; font-family: 'Playfair Display', serif;">
                            3</div>
                        <h4 style="color: var(--heading-color); font-weight: 700; margin-bottom: 15px;">Track Progress
                        </h4>
                        <p style="color: var(--text-muted); font-size: 14px; line-height: 1.6;">Follow your plan, update
                            your module status, and visualize your growing mastery in real-time analytics.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ════════════════════════════════════════
        STATS SECTION
        ════════════════════════════════════════ -->
    <section class="stats-section section-spacing" id="stats">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-6">
                    <div class="stat-item scroll-reveal delay-100">
                        <span class="stat-number" data-target="1000" data-suffix="+">1000+</span>
                        <div class="stat-label">Registered Students</div>
                    </div>
                </div>
                <div class="col-md-3 col-6">
                    <div class="stat-item scroll-reveal delay-200">
                        <span class="stat-number" data-target="5000" data-suffix="+">5000+</span>
                        <div class="stat-label">Schedules Generated</div>
                    </div>
                </div>
                <div class="col-md-3 col-6">
                    <div class="stat-item scroll-reveal delay-300">
                        <span class="stat-number" data-target="98" data-suffix="%">98%</span>
                        <div class="stat-label">Satisfaction</div>
                    </div>
                </div>
                <div class="col-md-3 col-6">
                    <div class="stat-item scroll-reveal delay-400">
                        <span class="stat-number">24/7</span>
                        <div class="stat-label">Available Support</div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ════════════════════════════════════════
        CTA SECTION
        ════════════════════════════════════════ -->
    <section class="cta-section-wrap">
        <div class="container">
            <div class="cta-card scroll-reveal">
                <h2>Ready to Transform Your Academic Success?</h2>
                <p>Join thousands of UCA students who are optimizing their learning with AI</p>
                <div class="btn-cta-group">
                    <a href="register.php" class="btn-cta-primary">
                        <i class="fas fa-rocket"></i> Create My Account
                    </a>
                    <a href="login.php" class="btn-cta-secondary">
                        <i class="fas fa-sign-in-alt"></i> Sign In
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- ════════════════════════════════════════
        FOOTER
        ════════════════════════════════════════ -->
    <footer class="footer-premium">
        <div class="container">
            <div class="row g-4 mb-4">
                <div class="col-md-4">
                    <div class="footer-brand anim-fade delay-200">
                        <img src="assets/images/universite-cadi-ayyad.png" alt="UCA">
                        <span>Edu-Planning</span>
                    </div>
                    <p style="color:rgba(255,255,255,0.55); font-size:14px; line-height:1.8;">
                        Intelligent academic platform developed for Université Cadi Ayyad of Marrakech. Powered by an
                        advanced AI.
                    </p>
                </div>
                <div class="col-md-4 offset-md-1">
                    <p class="footer-col-title">Quick Links</p>
                    <a href="#about" class="footer-link">About The Platform</a>
                    <a href="#features" class="footer-link">Key Features</a>
                    <a href="#how-it-works" class="footer-link">How It Works</a>
                    <a href="login.php" class="footer-link">Login</a>
                    <a href="register.php" class="footer-link">Sign Up</a>
                </div>
                <div class="col-md-3">
                    <p class="footer-col-title">Contact &amp; Support</p>
                    <p style="color:rgba(255,255,255,0.55); font-size:14px; margin-bottom:10px;">
                        <i class="fas fa-envelope"
                            style="color:#C8962E; margin-right:8px;"></i>support@edu-planning.uca.ma
                    </p>
                    <p style="color:rgba(255,255,255,0.55); font-size:14px;">
                        <i class="fas fa-map-marker-alt" style="color:#C8962E; margin-right:8px;"></i>
                        Marrakech, Safi, Maroc
                    </p>
                </div>
            </div>

            <div class="footer-bottom">
                <p>&copy; 2026 Université Cadi Ayyad — Marrakech. All rights reserved. | <strong
                        style="color:rgba(255,255,255,0.6);">Edu-Planning</strong></p>
            </div>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Smooth scroll for anchor links -->
    <script src="js/index.js"></script>

    <!-- App JS (scroll reveal, particles, navbar scroll, cursor, counters) -->
    <script src="js/app.js"></script>
    <!-- Three.js for STL rendering -->
    <script type="importmap">
        {
            "imports": {
                "three": "https://cdn.jsdelivr.net/npm/three@0.158.0/build/three.module.js",
                "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.158.0/examples/jsm/"
            }
        }
    </script>
    <script type="module">
        import * as THREE from 'three';
        import { STLLoader } from 'three/addons/loaders/STLLoader.js';
        import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

        const container = document.getElementById('stl-viewer');
        if (container) {
            const scene = new THREE.Scene();

            // Add elegant lighting
            const ambientLight = new THREE.AmbientLight(0xffffff, 1.2);
            scene.add(ambientLight);

            const dirLight = new THREE.DirectionalLight(0xffe699, 1.5);
            dirLight.position.set(20, 40, 50);
            scene.add(dirLight);

            const frontLight = new THREE.DirectionalLight(0xffffff, 1.0);
            frontLight.position.set(0, 0, 50);
            scene.add(frontLight);

            const backLight = new THREE.DirectionalLight(0xffdf80, 0.8);
            backLight.position.set(-20, -20, -50);
            scene.add(backLight);

            const camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 1000);
            camera.position.set(0, 0, 100);

            const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
            renderer.setSize(container.clientWidth, container.clientHeight);
            container.appendChild(renderer.domElement);

            const controls = new OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.autoRotate = true;
            controls.autoRotateSpeed = 2.0;
            controls.enableZoom = false;

            const loader = new STLLoader();
            loader.load('assets/images/icons_3d/icons.stl', function (geometry) {
                // Elegant Gold Material matching app style
                const material = new THREE.MeshStandardMaterial({
                    color: 0xB8860B, // Dark Goldenrod
                    metalness: 0.6,
                    roughness: 0.25
                });
                const mesh = new THREE.Mesh(geometry, material);

                geometry.computeBoundingBox();
                const box = geometry.boundingBox;
                const center = box.getCenter(new THREE.Vector3());
                geometry.translate(-center.x, -center.y, -center.z);

                const size = box.getSize(new THREE.Vector3()).length();
                const scale = 75 / size;
                mesh.scale.set(scale, scale, scale);

                // Set initial rotation so it faces the camera
                mesh.rotation.x = 0;
                mesh.rotation.y = 0;

                scene.add(mesh);
            }, undefined, function (error) {
                console.error('Error loading STL:', error);
            });

            function animate() {
                requestAnimationFrame(animate);
                controls.update();
                renderer.render(scene, camera);
            }
            animate();

            window.addEventListener('resize', () => {
                if (!container || !renderer) return;
                camera.aspect = container.clientWidth / container.clientHeight;
                camera.updateProjectionMatrix();
                renderer.setSize(container.clientWidth, container.clientHeight);
            });
        }
    </script>
    <script>
        // --- Advanced Mouse Follower (Animation de souris premium) ---
        const cursorDot = document.getElementById('cursor-dot');
        const cursorRing = document.getElementById('cursor-ring');

        if (cursorDot && cursorRing) {
            // Styling the advanced cursors
            cursorDot.style.position = 'fixed';
            cursorDot.style.width = '6px';
            cursorDot.style.height = '6px';
            cursorDot.style.backgroundColor = '#D4AF37';
            cursorDot.style.borderRadius = '50%';
            cursorDot.style.pointerEvents = 'none';
            cursorDot.style.transform = 'translate(-50%, -50%)';
            cursorDot.style.zIndex = '9999';
            cursorDot.style.transition = 'width 0.2s, height 0.2s';

            cursorRing.style.position = 'fixed';
            cursorRing.style.width = '36px';
            cursorRing.style.height = '36px';
            cursorRing.style.border = '1px solid rgba(212, 175, 55, 0.5)';
            cursorRing.style.borderRadius = '50%';
            cursorRing.style.pointerEvents = 'none';
            cursorRing.style.transform = 'translate(-50%, -50%)';
            cursorRing.style.zIndex = '9998';
            cursorRing.style.transition = 'width 0.3s, height 0.3s, border-color 0.3s, background-color 0.3s';
            cursorRing.style.boxShadow = '0 0 10px rgba(212, 175, 55, 0.2)';

            // Magnetic lag logic
            let mouseX = window.innerWidth / 2;
            let mouseY = window.innerHeight / 2;
            let ringX = mouseX;
            let ringY = mouseY;
            let isHovering = false;

            document.addEventListener('mousemove', (e) => {
                mouseX = e.clientX;
                mouseY = e.clientY;
                // Dot follows instantly
                cursorDot.style.left = mouseX + 'px';
                cursorDot.style.top = mouseY + 'px';
            });

            const renderCursor = () => {
                // Ring interpolates to mouse position (smooth delay)
                ringX += (mouseX - ringX) * 0.15;
                ringY += (mouseY - ringY) * 0.15;
                cursorRing.style.left = ringX + 'px';
                cursorRing.style.top = ringY + 'px';
                requestAnimationFrame(renderCursor);
            };
            requestAnimationFrame(renderCursor);

            // Interactive hover effect
            const interactables = document.querySelectorAll('a, button, input, .nav-link');
            interactables.forEach(el => {
                el.addEventListener('mouseenter', () => {
                    isHovering = true;
                    cursorDot.style.width = '0px';
                    cursorDot.style.height = '0px';

                    cursorRing.style.width = '50px';
                    cursorRing.style.height = '50px';
                    cursorRing.style.backgroundColor = 'rgba(212, 175, 55, 0.1)';
                    cursorRing.style.borderColor = '#D4AF37';
                });
                el.addEventListener('mouseleave', () => {
                    isHovering = false;
                    cursorDot.style.width = '6px';
                    cursorDot.style.height = '6px';

                    cursorRing.style.width = '36px';
                    cursorRing.style.height = '36px';
                    cursorRing.style.backgroundColor = 'transparent';
                    cursorRing.style.borderColor = 'rgba(212, 175, 55, 0.5)';
                });
            });

            // Hide default cursor globally for premium feel
            document.body.style.cursor = 'none';
            interactables.forEach(el => { el.style.cursor = 'none'; });
        }
    </script>
</body>

</html>